version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - server
        container_name: nginx
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - server
        container_name: php
networks:
    server:
        driver: bridge
